poporonnet/kcmsx

- .github/workflows/ci.yml
- package.json
close #71 
- pnpm/action-setupをやめて`corepack`を有効化した
> fix: pnpm/action-setupをcorepackで置き換え

- packages/kcms/src/entry/adaptor/dummyRepository.ts
- packages/kcms/src/entry/adaptor/json.ts
- packages/kcms/src/entry/controller.ts
- packages/kcms/src/entry/entry.test.ts
- packages/kcms/src/entry/entry.ts
- packages/kcms/src/entry/service/entry.test.ts
- packages/kcms/src/entry/service/get.test.ts
- packages/kcms/src/entry/service/get.ts
- packages/kcms/src/match/adaptor/dummyRepository.ts
- packages/kcms/src/match/adaptor/json.ts
- packages/kcms/src/match/controller.ts
- packages/kcms/src/match/match.test.ts
- packages/kcms/src/match/match.ts
- packages/kcms/src/match/service/edit.ts
- packages/kcms/src/match/service/generateFinal.test.ts
- packages/kcms/src/match/service/generateFinal.ts
- packages/kcms/src/match/service/generatePrimary.test.ts
- packages/kcms/src/match/service/generatePrimary.ts
- packages/kcms/src/match/service/generateRanking.test.ts
- packages/kcms/src/match/service/generateRanking.ts
- packages/kcms/src/match/service/get.test.ts
- packages/kcms/src/match/service/get.ts
close #76 
- Match/Entryモデルのゲッターセッターを普通の関数に置き換えました
- その他不要になった部分の削除も行っています
> refactor: モデルのゲッター/セッターを関数に置き換え

- packages/kcmsf/eslint.config.js
- packages/kcmsf/package.json
- pnpm-lock.yaml
close #98 
`@eslint/compat`を導入してv9で使用できるようにした
> fix: `eslint-plugin-react-hooks`をeslint v9に対応させる

- packages/config/tsconfig.json
- packages/kcms/tsconfig.json
close #174 
kcmsの`module`を`ESNext`に、`moduleResolution`を`bundler`に変更した
他のimportが壊れる可能性があるが、今のところ不具合は確認できず
> fix: kcmsからconfigパッケージを使用できるようにする

- packages/config/tsconfig.json
kcmsx/configの`tsconfig.json`の`taget`が`ESNext`になっていたので`ES2023`に変更しました
> fix: configの`target`を`ES2023`に修正

- packages/config/README.md
- packages/config/eslint.config.js
- packages/config/index.ts
- packages/config/package.json
- packages/config/src/utility/pick.test-d.ts
- packages/config/src/utility/pick.test.ts
- packages/config/src/utility/pick.ts
> feat: リテラルオブジェクトの配列から型安全に`map`をする`pick`を追加

- packages/kcms/src/match/model/pre.ts
- packages/kcms/src/match/service/generatePre.test.ts
- packages/kcms/src/match/service/generatePre.ts
- packages/kcms/src/team/controller.ts
- packages/kcms/src/team/main.ts
- packages/kcms/src/team/models/team.test.ts
- packages/kcms/src/team/models/team.ts
- packages/kcms/src/team/service/createTeam.test.ts
- packages/kcms/src/team/service/createTeam.ts
- packages/kcms/src/team/service/get.test.ts
- packages/kcms/src/team/service/get.ts
- packages/kcms/src/testData/entry.ts
close #178 
close #16
- #178 のアルゴリズムを実装
- 不要コードの削除
- 後から生成された部門で、コース番号が以前に生成された部門のコース番号と重複する(≒ 試合番号が重複する)状態になっています
- これについては別PRで修正する必要がありそうです
- テストが決めうちでconfigが変更されると落ちるようになっています
- ある程度動的に動作するようにしないといけなさそうです
> feat: 予選対戦表の生成ができるように

- packages/mock/src/main.ts
- packages/mock/wrangler.toml
CORSが`https://kcmsx.pages.dev`のみを許可していたので、プレビュービルド用に`https://*.kcmsx.pages.dev`も許可するようにした
> fix: Pagesのプレビュービルドからもmockが使えるように修正

- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/routing.ts
> feat: 試合の走行結果の追加のスキーマ定義

- packages/kcms/package.json
- packages/kcms/prisma/migrations/20241003090116_add_unique_team_name/migration.sql
- packages/kcms/prisma/schema.prisma
- packages/kcms/src/adaptor.ts
- packages/kcms/src/main.ts
- packages/kcms/src/team/adaptor/repository/prismaRepository.ts
- packages/kcms/src/team/controller.ts
- packages/kcms/src/team/main.ts
- packages/kcms/src/team/service/createTeam.test.ts
- packages/kcms/src/team/service/createTeam.ts
close #385 
- チーム登録エンドポイントの実装
- Controllerのミスを修正
- ハンドラの書き直し
- Nodeで実行できない問題への暫定対応をした
- Bunで直接TSを解釈する方法を採用
- このPRマージ後は暫定的にBunを実行環境に使用します
- nodeではサーバーの起動ができなくなります
> feat: チーム登録の実装, Nodeで実行できない問題への暫定対応

- packages/config/README.md
- packages/config/src/config.ts
- packages/config/src/types/conditionsConfig.ts
- packages/config/src/types/config.ts
- packages/config/src/types/departmentConfig.ts
- packages/config/src/types/matchConfig.ts
- packages/config/src/types/robotConfig.ts
- packages/config/src/types/ruleList.ts
- packages/config/src/utility/createConfig.test.ts
- packages/config/src/utility/createConfig.ts
- packages/config/src/utility/pick.ts
close #398
その他:
- `robotTypes`は`robots`から導出される形にして残しています。
- ↑に合わせ、`departmentTypes`と`matchTypes`も用意しました。
> feat: ロボットの設定で表示名を記述できる

- packages/config/src/config.ts
- packages/kcmsf/src/pages/match.tsx
close #397 
`multiWalk`は、`scorable`を使って得点が制御されるようになりました。
仕組み上初期値を`true`にせざるを得ず、エキシビションマッチでは最初から歩行型がチェックされた状態から始まります。
> feat: エキシビションマッチで歩行型かどうかを入力できる

- packages/kcms/src/main.ts
- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/main.ts
close #428  
- `GET /match`(全試合取得)を実装
- MainMatchは返していません
- MatchにdepartmentTypeを追加
> feat: MatchAPI.getAllMatchを実装

- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/main.ts
close #438 
- 試合取得エンドポイント(Controller/Handler)を実装
- 型推論が敗北したのでexportされていないスキーマをexportして使っています
> feat: 試合取得エンドポイントを実装

- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/main.ts
- packages/kcms/src/match/routing.ts
close #439
- `POST /match/{matchType}/{departmentType}/generate`の実装
- Routeの命名を訂正
> feat: 試合生成エンドポイントを実装

- packages/kcms/src/team/adaptor/controller/controller.ts
- packages/kcms/src/team/main.ts
close #436 
- エントリー用エンドポイントの実装
> feat: エントリーができるように(Controller/Handlerの実装)

- packages/kcmsf/package.json
- pnpm-lock.yaml
3.19.0の機能の影響でアイコンがすべてロードされていたため
暫定的な対処としてバージョンを3.17.0に固定し、tabler側で問題の解決がなされたら追従する
> chore: `@tabler/icons-react`を3.17.0にダウングレード

- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/main.ts
- packages/kcms/src/match/service/generateRanking.test.ts
- packages/kcms/src/match/service/generateRanking.ts
- packages/kcms/src/testData/match.ts
close #387 
- ランキングを生成できるように
- Controller/Handlerの実装
> feat: ランキング生成APIの実装

- packages/kcms/src/match/service/generateRanking.ts
- packages/kcms/src/testData/match.ts
- packages/kcmsf/src/pages/match.tsx
> fix: 左右入れ替えの片方しか終了していない場合でも予選ランキングが正しく計算されるように修正

- packages/kcmsf/src/pages/registerBulk.tsx
close #504 
見た目はスクリーンショットを見てください.
一括登録で登録できるCSVの制約を出すようにしました
> feat: 一括登録のサンプルを出すようにした

- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/main.ts
- packages/kcmsf/src/pages/teams.tsx
close #478 
指定した試合の走行結果を取得できるようになりました
> feat: 指定した試合の走行結果を実装

- packages/kcms/src/match/service/generateMain.test.ts
- packages/kcms/src/match/service/generateMain.ts
close #507 
- 本戦試合生成Serviceの実装
- そのテスト
> feat: 本戦試合生成Serviceの実装とテスト

- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/main.ts
- packages/kcms/src/match/routing.ts
close #546 
- 本戦試合の手動生成ができるようになりました
- `POST /match/main/{departmentType}/generate/manual`が生えました
> feat: 本戦試合の手動生成ができるように

- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/main.ts
- packages/kcms/src/match/service/generateRanking.test.ts
- packages/kcms/src/match/service/generateRanking.ts
- packages/kcms/src/testData/match.ts
close #555 
- 1試合しかない(=2チームしかない)ことを前提に予選とアルゴリズムを共通化
- (TODO) 本大会に向け、将来的にはトーナメント用アルゴリズムに書き換える必要がある
- #571 のため現在実際の動作は確認できない
> feat: (安来用)本戦試合のランキングを取得できる

- packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
- packages/kcms/src/match/adaptor/prisma/preMatchRepository.ts
- packages/kcms/src/match/model/main.test.ts
- packages/kcms/src/match/model/main.ts
close #571 
- `prisma/*MatchRepository.appendRunResults`の実装が誤っていたが、テストは`DummyRepository`を用いているためテスト不可能
> fix:MainMatchに走行結果を追加できるよう変更

- packages/kcmsf/src/components/GenerateMainMatchCard.tsx
- packages/kcmsf/src/hooks/useFetch.ts
- packages/kcmsf/src/pages/matchList.tsx
- packages/kcmsf/src/pages/ranking.tsx
- packages/kcmsf/src/pages/result.tsx
- packages/kcmsf/src/pages/teams.tsx
- packages/kcmsf/tsconfig.json
close #613
close #117  
- `useFetch`フックを作りました
- ロード時に発火していたfetchを`useFetch`に置き換えました
- `Error.cause`が使いたかったためtargetをESNextに上げました
> refactor: データフェッチをカスタムフック化

- packages/kcmsf/vite.config.ts
cf. #470 
- バージョンを固定するためにはrenovateの設定を変更しなければならない
- renovateの設定を変更したくないため、パスエイリアスで動的importを行わないように変更した
> chore: tabler-iconsが動的importを行わないように設定

- packages/kcmsf/src/components/LabeledSegmentedControl.tsx
- packages/kcmsf/src/components/LabeledSegmentedControls.tsx
- packages/kcmsf/src/pages/matchList.tsx
- packages/kcmsf/src/pages/ranking.tsx
close #720 
-  レイアウトに内部的にTableを使用するようになりました
- 今後各種`***SegmentedControl`を使うときは`LabeledSegmentedControls`で包む必要があります
> fix: LabeledSegmentedControlが適切な幅で表示される

- packages/kcms/README.md
- packages/kcms/src/main.ts
- packages/kcmsf/src/App.tsx
- packages/kcmsf/src/components/AuthProvider.tsx
- packages/kcmsf/src/components/Login.tsx
- packages/kcmsf/src/components/match/matchSubmit.tsx
- packages/kcmsf/src/hooks/useAuth.ts
- packages/kcmsf/src/hooks/useFetch.ts
- packages/kcmsf/src/hooks/useMatchInfo.ts
- packages/kcmsf/src/pages/matchList.tsx
- packages/kcmsf/src/pages/ranking.tsx
- packages/kcmsf/src/pages/register.tsx
- packages/kcmsf/src/pages/registerBulk.tsx
- packages/kcmsf/src/pages/teams.tsx
- packages/mock/src/main.ts
close #623 
- フロントエンドに認証を掛けた
- ブラウザのポップアップを回避するためバックエンドにも手を入れています
- Basic Authの認証スキームを`KCMS-Basic`に差し替えています
> feat: フロントエンドに認証を追加

- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/main.ts
- packages/kcms/src/match/model/main.ts
- packages/kcms/src/match/service/generateMain.test.ts
- packages/kcms/src/match/service/generateMain.ts
- packages/kcms/src/match/utility/eachSlice.test.ts
- packages/kcms/src/match/utility/eachSlice.ts
close #618 
- 試合生成方式を2チーム手動設定からnチーム(configで設定する)トーナメントに変更
- それに伴うコードの修正
- 現在は全て1-1として生成
- (このPRでは対応しない) 人数が2冪の値でないときの穴埋め処理
手動本戦試合生成エンドポイントのスキーマを変更.
```diff
{
-  teamID1: string,
-  teamID2: string
+  teamIDs: string[]
}
```
※ teamIDs: 予選までの順位でソートされているものとみなして処理します。
> feat!(api,service): 本戦試合生成をトーナメント方式に変更

- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/main.ts
- packages/kcms/src/match/model/main.test.ts
- packages/kcms/src/match/model/main.ts
- packages/kcms/src/match/routing.ts
- packages/kcms/src/match/service/setMainWinner.test.ts
- packages/kcms/src/match/service/setMainWinner.ts
- MainMatchモデルにsetTeams(teamID1, teamID2)を追加
- SetMainMatchWinnerServiceを実装
- 終了した試合にwinnerIDを設定する
- 同じ親を持つもう一方の試合が終了している場合は、親試合のチームを設定する
> chore: SetMainMatchWinnerServiceを実装

- .github/workflows/ci.yml
- package.json
- packages/config/package.json
- packages/kcms/package.json
- packages/kcmsf/package.json
- packages/mock/package.json
> chore(ci): `packageManager`フィールドにハッシュ値を含め、最新のcorepackを使用する

- packages/kcmsf/src/pages/home.tsx
- packages/kcmsf/src/pages/matchList.tsx
- packages/kcmsf/src/pages/ranking.tsx
- packages/kcmsf/src/pages/register.tsx
- packages/kcmsf/src/pages/registerBulk.tsx
- packages/kcmsf/src/pages/result.tsx
- packages/kcmsf/src/pages/teams.tsx
- packages/kcmsf/src/pages/tournament.tsx
close #1214
試合表・チーム一覧のページのレイアウトに統一してみました
トーナメントページで`flex: 1`が追加で必要になるのでコンポーネントにはしていません(したほうがいい？)
> feat: 試合ページ以外を試合表ページと同じレイアウトに統一
