- packages/kcmsf/index.html
close #1  
HTMLのlangをenからjaに変更した。
> chore: サイトの言語を日本語に変更した

- packages/kcmsf/index.html
close #2 
サイトのタイトルがデフォルトの React + Vite + TS になっていたのを kcmsxに変更
> chore:サイトのタイトルをデフォルトからkcmsxに変更した

- packages/kcmsf/src/config/types/rule.ts
- packages/kcmsf/src/pages/home.tsx
close #103 
/に各機能ごとのページのリンクを追加した。
> feat: /に各機能ごとのページへのリンクを書いた

- packages/kcmsf/src/pages/home.tsx
- packages/kcmsf/src/routes/router.tsx
close #104
nested routerをbrowser routerに置き換えた
> chore: nested routerをbrowser routerに置き換えた

- packages/kcmsf/src/pages/matchList.tsx
- packages/kcmsf/tsconfig.json
> chore(format): フロントエンドにフォーマットを掛けた

- .github/workflows/ci.yml
- packages/kcmsf/package.json
> feat(ci): フロントエンドのフォーマットチェックを追加

- packages/config/eslint.config.js
- packages/config/src/types/derived/config.ts
- packages/kcmsf/src/pages/matchList.tsx
> fix: tseslint v8で増えたlintのerrorの修正

- packages/kcms/src/entry/entry.test.ts
- packages/kcms/src/entry/entry.ts
- packages/kcms/src/entry/service/entry.ts
close #26 
- EntryにclubNameを追加しました
- Undefinedを許容するようにしています
> feat: Entryにクラブ を追加

- packages/kcms/src/entry/main.ts
- packages/kcms/src/entry/schema.ts
> feat: バルクエントリーの実装

- packages/kcms/src/match/model/runResult.test.ts
- packages/kcms/src/match/model/runResult.ts
> fix: FinishStateの変更

- packages/mock/README.md
- packages/mock/package.json
> chore:ポート番号を指定

- packages/kcms/src/team/adaptor/validator/team.ts
- packages/kcms/src/team/routing.ts
> feat: エントリースキーマの定義

- packages/kcms/src/team/adaptor/validator/team.ts
- packages/kcms/src/team/routing.ts
> feat:エントリー削除のスキーマを定義

- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/routing.ts
> fix: 変数名の変更

- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/routing.ts
matchIdになっていた部分をmatchIDに統一する流れに伴い一部変更しました
> chore: matchid をmatchIDに統一した

- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/routing.ts
> feat: 試合表生成のスキーマを定義

- packages/mock/src/data/team.ts
- packages/mock/src/main.ts
close #405 
その他: `POST /team`周りの誤りを修正
> fix: `entryId`を`entryCode`に修正

- packages/kcmsf/src/pages/match.tsx
close #396
その他: `GET /match/{matchType}/{matchID}`のAPIの修正に対応
> fix: 試合の終了条件にフィニッシュを含める

- packages/kcmsf/src/components/header.tsx
> feat: ヘッダーにトップへのリンクを設置

- packages/config/src/types/conditionsConfig.ts
- packages/config/src/types/derived/matchInfo.ts
- packages/config/src/types/derived/premise.ts
- packages/config/src/types/matchInfo.ts
- packages/config/src/types/premise.ts
- packages/config/src/types/rule.ts
- packages/config/src/utility/createConfig.test.ts
- packages/kcmsf/src/pages/match.tsx
> fix: `TeamInfo`のプロパティを`robotType`と`departmentType`に変更

- packages/kcmsf/src/pages/match.tsx
close #417 
https://fix-417-math-page-main.kcmsx.pages.dev/match/pre/6582553
https://fix-417-math-page-main.kcmsx.pages.dev/match/main/943629
> fix: 本戦試合を表示できる

- docs/api.md
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/mock/src/data/match.ts
close #421 
- mockのデータに`departmentType`を追加
- スキーマに`departmentType`を追加
> fix: matchにdepartmentTypeを追加

- packages/kcmsf/src/routes/router.tsx
close #172 
routerのパスをentryからregisterに変更した
> fix: registerに名称変更をした

- packages/kcmsf/src/components/header.test.tsx
- packages/kcmsf/src/components/header.tsx
- packages/kcmsf/src/pages/home.tsx
ホームとヘッダーにあったリンクをentryからregisterに変更した
> fix: リンクを修正

- packages/kcms/src/team/controller.ts
- packages/kcms/src/team/main.ts
- packages/kcms/src/team/service/get.test.ts
- packages/kcms/src/team/service/get.ts
close #434 
GET /team/{teamID}
関数名をgetOneにした
controllerとhandlerの実装
> feat:チーム取得のController/Handlerを実装

- packages/kcms/src/team/main.ts
> feat: DELETE /team/{teamID}のhandlerを実装

- packages/kcms/prisma/migrations/20241008085516_add_department_match_type_to_prematch/migration.sql
- packages/kcms/prisma/migrations/20241008090747_remove_match_type_from_prematch/migration.sql
- packages/kcms/prisma/schema.prisma
- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/dummy/preMatchRepository.test.ts
- packages/kcms/src/match/adaptor/prisma/preMatchRepository.ts
- packages/kcms/src/match/model/pre.test.ts
- packages/kcms/src/match/model/pre.ts
- packages/kcms/src/match/service/generatePre.ts
- packages/kcms/src/testData/match.ts
close #440 
- PreMatchにdepartmentTypeを追加
- DBスキーマを更新
> feat: PreMatchにdepartmentTypeを追加

- packages/kcms/src/team/adaptor/controller/controller.ts
- packages/kcms/src/team/main.ts
close #461 
エントリーキャンセルのボタンを押せばエントリーが解除されるようになった
> feat:エントリーキャンセルの実装

- packages/kcms/package.json
- packages/kcms/src/match/main.ts
- packages/kcms/src/team/main.ts
- pnpm-lock.yaml
- openapi.json
- `/openapi/team.json`
- `/openapi/match.json`
- scalar
- `/reference/team`
- `/reference/match`
> feat: APIドキュメントページを追加

- packages/mock/src/data/match.ts
- packages/mock/src/data/team.ts
close #469 
再発防止のためconfigを使用して型定義を行った
その他軽微な修正
> fix: `departmentType`をconfigの値と一致させる

- packages/kcmsf/src/pages/match.tsx
> fix: エキシビションマッチでは採点UIを無効化しないように修正

- packages/kcmsf/src/routes/layout.tsx
close #477 
権利表記を更新  
`kcms ©️2023 Poporon Network` -> `kcms ©️2023-2024 Poporon Network`
> feat: 著作権表記を更新

- packages/kcmsf/src/pages/teams.tsx
> chore: チーム一覧ページのロボット種別のフィルターをconfigから引用

- packages/kcmsf/src/pages/match.tsx
- packages/kcmsf/src/pages/register.tsx
- packages/kcmsf/src/pages/result.tsx
- packages/kcmsf/src/pages/teams.tsx
- packages/kcmsf/src/types/match.ts
> chore: 各ページで定義していた型をAPI型定義に置き換えた

- packages/kcmsf/src/components/match/PointControl.tsx
- packages/kcmsf/src/components/match/PointCountable.tsx
- packages/kcmsf/src/components/match/PointSingle.tsx
- packages/kcmsf/src/pages/match.tsx
- packages/kcmsf/src/utils/match/point.ts
- packages/kcmsf/src/utils/match/team.ts
> feat: 得点リセットボタン

- packages/config/src/config.ts
> fix: 本戦のみ先ゴールに1点を与えるように修正

- packages/kcmsf/src/components/courseSelector.tsx
- packages/kcmsf/src/index.css
- packages/kcmsf/src/pages/matchList.tsx
- packages/kcmsf/src/pages/teams.tsx
close #34
- 軽微な修正
- モーダルが正しく表示されなかったため、デフォルトのスタイルを変更
- 既存のページに影響が出ないようにしたつもりですが、全パターンは試せていません。
> feat: 試合生成ボタン

- docs/api.md
- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcmsf/src/types/match.ts
- packages/mock/src/data/match.ts
> feat: PreMatchのAPIに`matchType`を追加した

- packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
- packages/kcms/src/match/adaptor/prisma/preMatchRepository.ts
close #502 
`goalTimeSeconds`の`Infinity`を`2147483647`に変換
> fix:goalTimeSecondsのInfinityを変換

- packages/kcmsf/src/pages/ranking.tsx
- pnpm-lock.yaml
close #503 
rankingのゴールタイムをベストタイムにした
> chore: ゴールタイムをベストタイムにリネーム

- packages/kcms/src/match/adaptor/controller/match.ts
> feat: 試合の取得(`GET /match`, `GET /match/{matchType}/{matchID}`)でMainMatchも取得する

- packages/kcmsf/src/pages/ranking.tsx
> fix: 本戦試合生成リクエストのヘッダに`"Content-Type": "application/json"`を追加

- packages/kcmsf/src/components/DepartmentSegmentedControl.tsx
- packages/kcmsf/src/components/LabeledSegmentedControl.tsx
- packages/kcmsf/src/components/MatchTypeSegmentedControl.tsx
- packages/kcmsf/src/components/matchStatus.tsx
- packages/kcmsf/src/pages/matchList.tsx
- packages/kcmsf/src/pages/ranking.tsx
close #556 
- いくつかのSegmentedControlをコンポーネント化しました。
- 各ページでもこれを使いたい
- `/matchlist`にクエリパラメータ`match_type`を追加しました。
- `/matchlist?match_type=main`のように使う
> feat: 試合一覧ページで本戦試合を表示する

- packages/kcmsf/src/pages/matchList.tsx
> feat: 試合一覧ページの試合生成ボタンを予選選択時にしか押せないように

- packages/kcmsf/src/components/GenerateMainMatchCard.tsx
- packages/kcmsf/src/pages/ranking.tsx
> feat: 本戦試合が存在しているときは本戦試合を生成できないように

- packages/kcmsf/src/components/GenerateMainMatchCard.tsx
> fix: 本戦試合が存在することを見る条件式を正しいものに修正

- packages/kcmsf/src/pages/result.tsx
- packages/mock/src/data/match.ts
- packages/mock/src/data/runResult.ts
> fix:試合結果のゴールタイムの表示を修正した

- packages/kcmsf/src/pages/ranking.tsx
> fix: 予選ランキングにしかチェックボックスを表示しないように

- packages/kcmsf/src/pages/result.tsx
> fix:試合結果がない場合の表示を変更

- packages/kcmsf/src/pages/result.tsx
> fix:ポイントを勝者ID,敗者IDで探すように変更

- packages/kcmsf/src/components/match/matchSubmit.tsx
- packages/kcmsf/src/hooks/useJudge.ts
- packages/kcmsf/src/hooks/useMatchInfo.ts
- packages/kcmsf/src/hooks/useMatchTimer.ts
- packages/kcmsf/src/pages/match.tsx
close #597 
その他
- ロジックをカスタムフックに分離
- 走行結果送信後に試合表に遷移するように
> feat: 本戦試合2回目を考慮した表示

- packages/kcmsf/package.json
- pnpm-lock.yaml
> Revert "chore(deps): update dependency @tabler/icons-react to v3.20.0"

- packages/kcmsf/src/components/header.test.tsx
- packages/kcmsf/src/components/header.tsx
- packages/kcmsf/src/pages/result.tsx
> feat:590 ヘッダーに不足しているリンクを追加した

- packages/kcms/package.json
- packages/kcmsf/.env.production
- packages/kcmsf/README.md
- packages/kcmsf/package.json
- pnpm-lock.yaml
- 安来運用のために行った変更
- 今後もこの形式で提供するのがよいのでは
- なんか意見ください
> feat: ローカルホスティングのための機能を追加

- packages/kcmsf/src/components/RouterLink.tsx
- packages/kcmsf/src/components/RouterNavLink.tsx
- packages/kcmsf/src/components/header.tsx
- packages/kcmsf/src/components/matchStatus.tsx
- packages/kcmsf/src/index.css
- packages/kcmsf/src/pages/home.tsx
> feat: ホーム画面のリンクを整理

- packages/mock/src/data/match.ts
> fix: mockの本戦試合のidを修正

- packages/kcms/src/match/main.ts
- packages/kcms/src/team/main.ts
> chore: DummyRepositoryを使わない

- packages/config/src/config.ts
close #787 
- オープン部門に車輪型を追加
- コンテスト名を変更
> chore:オープン部門に車輪型を追加

- packages/kcmsf/src/pages/matchList.tsx
> feat: 試合一覧ページで部門を選択できる

- packages/kcms/prisma/schema.prisma
- packages/kcms/src/match/adaptor/controller/match.ts
- packages/kcms/src/match/adaptor/validator/match.ts
- packages/kcms/src/match/main.ts
- packages/kcms/src/match/routing.ts
- packages/kcms/src/match/service/fetchTournament.test.ts
- packages/kcms/src/match/service/fetchTournament.ts
> feat: 本戦トーナメント取得(`GET /match/main/{departmentType}/tournament`)を実装

- packages/kcms/src/match/adaptor/controller/match.ts
> fix: 試合のチームが空の場合に対応

- .github/workflows/cd-for-fork.yaml
close #1185 
マージしてみないと動くかわかりません😸
> fix(cd): wrangler-actionが参照するディレクトリを修正

- .github/workflows/cd-for-fork.yaml
> fix(cd): ビルドコマンドでstagingモードを使うよう修正

- packages/kcmsf/src/components/header.test.tsx
- packages/kcmsf/src/components/header.tsx
- packages/kcmsf/src/pages/home.tsx
- packages/kcmsf/src/pages/registerBulk.tsx
- 参加者という文言をチームに変更
- 一括エントリーという文言を一括登録に変更
close #1339
> feat: 参加者という文言をチームに変更
